import type { Env } from '../types/env';
import { renderPlaceholderHtml } from '../dashboard/renderer';
import { createCorsHeaders } from './cors';

const DASHBOARD_KV_KEY = 'dashboard:html';

/**
 * Handles GET /dashboard — serves the static HTML dashboard pre-generated by background cron.
 * Strictly reads from Cloudflare KV. Never runs live D1 queries on public request.
 */
export async function handleDashboardRequest(
  _request: Request,
  env: Env,
  _ctx?: ExecutionContext
): Promise<Response> {
  let html: string | null = null;

  // 1. Fast KV cache read
  if (env.CACHE_KV) {
    try {
      html = await env.CACHE_KV.get(DASHBOARD_KV_KEY, { type: 'text' });
    } catch (err) {
      console.warn('[Dashboard] KV read failed:', err);
    }
  }

  // 2. Return cached dashboard HTML if available
  if (html) {
    return new Response(html, {
      status: 200,
      headers: createCorsHeaders({
        'Content-Type': 'text/html; charset=utf-8',
        'Cache-Control': 'public, max-age=3600, stale-while-revalidate=600',
      }),
    });
  }

  // 3. Cold start fallback: render placeholder HTML while awaiting scheduled cron generation
  return new Response(renderPlaceholderHtml(), {
    status: 200,
    headers: createCorsHeaders({
      'Content-Type': 'text/html; charset=utf-8',
      'Retry-After': '60',
      'Cache-Control': 'public, max-age=60, stale-while-revalidate=300',
    }),
  });
}

