import { renderLandingHtml } from '../landing/renderer';
import type { Env } from '../types/env';
import { DEFAULT_UPSTREAM_RELAYS } from '../upstream/pool-manager';
import {
  APP_CONTACT,
  APP_DESCRIPTION,
  APP_NAME,
} from '../version';
import { createCorsHeaders } from './cors';

/**
 * Handles GET / requests for browsers and HTML consumers.
 * Strictly reads summary telemetry from Cloudflare KV (pre-generated by background cron).
 * Never runs live D1 queries on public landing page visits.
 */
export async function handleLandingRequest(
  _request: Request,
  env: Env,
  _ctx?: ExecutionContext
): Promise<Response> {
  const relayName = env.RELAY_NAME || APP_NAME;
  const relayDescription = env.RELAY_DESCRIPTION || APP_DESCRIPTION;
  const relayContact = env.RELAY_CONTACT || APP_CONTACT;
  const relayPubkey = env.RELAY_PUBKEY || '';

  let totalEvents: number | undefined;
  let totalAuthors: number | undefined;
  let totalTags: number | undefined;
  let indexedVectors: number | undefined;

  // 1. Read summary from KV cache if available
  if (env.CACHE_KV) {
    try {
      const cached = await env.CACHE_KV.get('stats:summary', 'json');
      if (cached && typeof cached === 'object') {
        const s = cached as {
          total_events?: number;
          total_authors?: number;
          total_tags?: number;
          indexed_vectors?: number;
        };
        totalEvents = s.total_events;
        totalAuthors = s.total_authors;
        totalTags = s.total_tags;
        indexedVectors = s.indexed_vectors;
      }
    } catch (err) {
      console.warn('[Landing] KV summary cache read failed:', err);
    }
  }

  const configuredUpstreams = env.UPSTREAM_RELAYS
    ? env.UPSTREAM_RELAYS.split(',').map((s) => s.trim()).filter(Boolean)
    : DEFAULT_UPSTREAM_RELAYS;

  const kvStatus: 'active' | 'disabled' = env.CACHE_KV ? 'active' : 'disabled';

  const html = renderLandingHtml({
    relayName,
    relayDescription,
    relayContact,
    relayPubkey,
    stats: {
      totalEvents,
      totalAuthors,
      totalTags,
      indexedVectors,
      upstreamCount: configuredUpstreams.length,
      kvStatus,
      gcSchedule: 'Daily at 03:00 UTC',
    },
    upstreams: configuredUpstreams,
    supportedNips: [1, 9, 11, 16, 20, 33, 50, 65],
  });

  const headers = createCorsHeaders({
    'Content-Type': 'text/html; charset=utf-8',
    'Cache-Control': 'public, max-age=300, stale-while-revalidate=600',
  });

  return new Response(html, {
    status: 200,
    headers,
  });
}

